update=10/16/2013 11:08:20 PM
last_client=pcbnew
[eeschema]
version=1
PageLayoutDescrFile=
SubpartIdSeparator=0
SubpartFirstId=65
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=library/w_vacuum
LibName2=library/device
LibName3=library/power
LibName4=library/RT7247B
LibName5=library/w_analog
LibName6=library/w_connectors
LibName7=library/w_device
LibName8=library/w_logic
LibName9=library/w_memory
LibName10=library/w_microcontrollers
LibName11=library/w_opto
LibName12=library/w_relay
LibName13=library/w_rtx
LibName14=library/w_transistor
[cvpcb]
version=1
NetIExt=net
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=../../rPi_audio_board_V0.9.net
UseCmpFile=1
PadDrill=0
PadDrillOvalY=0
PadSizeH=1.2
PadSizeV=1.2
PcbTextSizeV=1
PcbTextSizeH=1
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.00254
SolderMaskMinWidth=0
DrawSegmentWidth=0.15
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[pcbnew/libraries]
LibDir=
LibName1=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/capacitors
LibName2=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/connect
LibName3=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/connectors_molex_serial_53047-A123
LibName4=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/dip_sockets
LibName5=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/discret
LibName6=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/display
LibName7=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/divers
LibName8=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/inductors
LibName9=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/led
LibName10=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/libcms
LibName11=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/muonde
LibName12=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/Neutrik
LibName13=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/pasdesignal
LibName14=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/pga_sockets
LibName15=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/pin_array
LibName16=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/powerint
LibName17=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/smd_capacitors
LibName18=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/smd_crystal&oscillator
LibName19=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/smd_dil
LibName20=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/smd_resistors
LibName21=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/smd_soic_packages
LibName22=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/smd_ssop_packages
LibName23=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/smd_transistors
LibName24=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/sockets
LibName25=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/valves
LibName26=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_battery_holders
LibName27=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_capacitors
LibName28=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_9159
LibName29=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_av
LibName30=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_df12
LibName31=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_df13
LibName32=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_d-sub
LibName33=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_jst-ph
LibName34=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_kk100
LibName35=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_misc
LibName36=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_modu
LibName37=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_mpt
LibName38=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_panelmate
LibName39=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_pc
LibName40=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_pt-1,5
LibName41=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_rf
LibName42=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_screw
LibName43=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_conn_strip
LibName44=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_crystal
LibName45=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_details
LibName46=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_indicators
LibName47=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_logo
LibName48=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_misc_comp
LibName49=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_misc_rf
LibName50=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_pin_strip
LibName51=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_pth_circuits
LibName52=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_pth_diodes
LibName53=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_pth_plcc
LibName54=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_pth_resistors
LibName55=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_relay
LibName56=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_bga
LibName57=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_cap
LibName58=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_dil
LibName59=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_diode
LibName60=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_inductors
LibName61=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_leds
LibName62=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_lqfp
LibName63=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_plcc
LibName64=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_qfn
LibName65=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_resistors
LibName66=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_strip
LibName67=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_smd_trans
LibName68=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_switch
LibName69=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_to
LibName70=C:/Documents and Settings/skypetest/My Documents/Dropbox/Git/rPI_audio_board/modules/w_vacuum
